/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Health
         * @description Liveness probe.
         */
        get: operations["get_health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Config
         * @description Public config: provider and model names only, never keys.
         */
        get: operations["get_config_api_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Runs
         * @description List runs, oldest first. ``?demo=true`` shows only demo runs.
         */
        get: operations["get_runs_api_runs_get"];
        put?: never;
        /**
         * Create Run
         * @description Accept a paper PDF and start the pipeline in a background worker.
         */
        post: operations["create_run_api_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Run
         * @description Run detail with per-stage status, timestamps and errors.
         */
        get: operations["get_run_api_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream Run Events
         * @description SSE stream: replay ``events.jsonl``, then stream live events.
         */
        get: operations["stream_run_events_api_runs__run_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/code": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Run Code
         * @description File tree of generated code per claim and iteration (server-enumerated).
         */
        get: operations["get_run_code_api_runs__run_id__code_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/code/{claim_id}/{iteration}/{file_index}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Run Code File
         * @description File content from the server-enumerated code tree.
         *
         *     Files resolve only from the enumeration above, never from a raw
         *     path, so ``..`` segments and unknown names return 404.
         */
        get: operations["get_run_code_file_api_runs__run_id__code__claim_id___iteration___file_index__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/{artifact}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Run Artifact
         * @description Fetch one run artifact. Names are whitelisted; paths are fixed.
         */
        get: operations["get_run_artifact_api_runs__run_id___artifact__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel Run
         * @description Cancel a queued or running run.
         */
        post: operations["cancel_run_api_runs__run_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_create_run_api_runs_post */
        Body_create_run_api_runs_post: {
            /** File */
            file: string;
        };
        /**
         * CodeClaim
         * @description Generated code for one claim across iterations.
         */
        CodeClaim: {
            /** Claim Id */
            claim_id: string;
            /**
             * Iterations
             * @default []
             */
            iterations: components["schemas"]["CodeIteration"][];
        };
        /**
         * CodeFile
         * @description One generated code file, addressed by server-assigned index.
         */
        CodeFile: {
            /** Index */
            index: number;
            /** Name */
            name: string;
            /** Size */
            size: number;
        };
        /**
         * CodeIteration
         * @description One saved iteration of a claim's generated code.
         */
        CodeIteration: {
            /** Iteration */
            iteration: number;
            /**
             * Files
             * @default []
             */
            files: components["schemas"]["CodeFile"][];
        };
        /**
         * CodeTree
         * @description File tree of generated code, enumerated by the server.
         */
        CodeTree: {
            /** Run Id */
            run_id: string;
            /**
             * Claims
             * @default []
             */
            claims: components["schemas"]["CodeClaim"][];
        };
        /**
         * ConfigInfo
         * @description Public runtime config. Never includes API keys.
         */
        ConfigInfo: {
            /** Provider */
            provider: string;
            /** Model Planner */
            model_planner: string;
            /** Model Agent */
            model_agent: string;
            /** Model Fast */
            model_fast: string;
        };
        /**
         * CreateRunResponse
         * @description Ids for a newly accepted run.
         */
        CreateRunResponse: {
            /** Run Id */
            run_id: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * Health
         * @description Liveness response.
         */
        Health: {
            /** Status */
            status: string;
        };
        /**
         * RunDetail
         * @description Full run state including per-stage status.
         */
        RunDetail: {
            /** Run Id */
            run_id: string;
            /** Status */
            status: string;
            /**
             * Demo
             * @default false
             */
            demo: boolean;
            /**
             * Filename
             * @default
             */
            filename: string;
            /**
             * Created At
             * @default
             */
            created_at: string;
            /**
             * Updated At
             * @default
             */
            updated_at: string;
            /** Error */
            error?: string | null;
            /**
             * Stages
             * @default {}
             */
            stages: {
                [key: string]: components["schemas"]["StageState"];
            };
        };
        /**
         * RunSummary
         * @description One row of the run list.
         */
        RunSummary: {
            /** Run Id */
            run_id: string;
            /** Status */
            status: string;
            /**
             * Demo
             * @default false
             */
            demo: boolean;
            /**
             * Filename
             * @default
             */
            filename: string;
            /**
             * Created At
             * @default
             */
            created_at: string;
            /**
             * Updated At
             * @default
             */
            updated_at: string;
        };
        /**
         * StageState
         * @description Status and timestamps for one pipeline stage.
         */
        StageState: {
            /** Status */
            status: string;
            /** Started At */
            started_at?: string | null;
            /** Ended At */
            ended_at?: string | null;
            /** Error */
            error?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    get_config_api_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigInfo"];
                };
            };
        };
    };
    get_runs_api_runs_get: {
        parameters: {
            query?: {
                demo?: boolean | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_run_api_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_create_run_api_runs_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateRunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_api_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_run_events_api_runs__run_id__events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_code_api_runs__run_id__code_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CodeTree"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_code_file_api_runs__run_id__code__claim_id___iteration___file_index__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
                claim_id: string;
                iteration: number;
                file_index: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_artifact_api_runs__run_id___artifact__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
                artifact: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_run_api_runs__run_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
